# Generated by Django 3.1.7 on 2021-06-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
