# Generated by Django 3.1.7 on 2021-06-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210602_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
