# Generated by Django 3.1.7 on 2021-05-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210323_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Treatment',
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name_plural': 'Treatments'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='category',
            new_name='treatment',
        ),
    ]
