# Generated by Django 3.1.7 on 2021-06-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210526_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={},
        ),
    ]
